POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "first_name":"Xinhao",
    "last_name":"Chen",
    "user_id":1,
    "email_address":"mendes@mail.com",
    "password":"123"
}